name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lix-pm/setup-lix@master
    - uses: HaxeFlixel/setup-flixel@master
      with:
        haxe-version: 4.2.1
        flixel-versions: release
        target: flash
    - run: npm install
      working-directory: api/dox
    - run: haxe --cwd api --run Make xml pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./api/dox/out
        cname: api.haxeflixel.com
